[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' pnpm run build:light"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "22"
  NPM_FLAGS = "--production=false"

[functions]
  # Set to the directory where your functions are located
  directory = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200